stages:
  - test

  
test-unit:
  stage: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
  - apt-get update -qy
  - apt-get install -y python3.8-dev python-pip
  - python3.8 -m pip install --upgrade pip
  - python3.8 -m pip install -r requirements.txt
  - python3.8 manage.py test tests
  
test-integration:
  stage: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
  - apt-get update -qy
  - apt-get install -y python3.8-dev python-pip
  - python3.8 -m pip install --upgrade pip
  - python3.8 -m pip install -r requirements.txt
  - python3.8 manage.py test tests_integration
  