version: '3.4'

services:
  joggingtracker:
    image: joggingtracker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/jogging
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=jogging
    # command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user jogging"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - 5432:5432

volumes:
  postgres_data: